# Generated by Django 4.2.1 on 2023-07-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appSales", "0006_alter_brand_image_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(upload_to="appSales/static/images/brand/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="appSales/static/images/category/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="appSales/static/images/product/"),
        ),
    ]
