# Generated by Django 4.2.1 on 2023-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appSales", "0007_alter_brand_image_alter_category_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
