# Generated by Django 4.2.2 on 2023-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appSales", "0008_product_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="img",
            field=models.ImageField(upload_to="appSales/static/images/banner/"),
        ),
    ]
